### ISSUE TITLE
Upgrade nueva versión

### ISSUE THREAD

**Issue by simber72** [DiasporeUnizar/TEG#10]

**Comment by simber72** [comment]
Si la versión en la rama Sparse pasa el test (test_detector_comparer_TEG con todas las métricas):

- Hacer un merge con el main de esta versión 
- Actualizar la versión (1.1.0?)
- Crear la distribución (/dist)
- Crear la etiqueta correspondiente

**Comment by 844759** [comment]
Hola Simona,

He visto que la versión que hay actualmente en Sparse, pasa todos los test sin problema alguno, por lo cual se puede realizar merge de la versión de Sparse, en cuanto me des el visto bueno hago el merge de esta rama, también voy a crear la rama para el diseño de ventanas deslizantes que mencionamos.

Un saludo,

Ángel

**Comment by 844759** [comment]
Hola Simona,

Ya he realizado el merge, la actualización, he creado dist usando setup.py y he creado la etiqueta correspondiente.

Un saludo,
Ángel,

**Comment by simber72** [comment]
La nueva versión está también en Pypi:
https://pypi.org/project/tegdet/


Simona
