### ISSUE TITLE
Adaptar programas de prueba a SlidingWindow

### ISSUE THREAD

**Issue by 844759** [DiasporeUnizar/TEG#14]

**Comment by 844759** [comment]
Hola Simona,

De momento he realizado la adaptación del script de test_detector_comparer_TEG.py para añadir la lógica de ventana deslizante, estoy comprobando si todo se realiza correctamente, pero he podido generar ya los primeros resultados de la ejecución mediante esta metodología, aunque es pronto para determinar la corrección de los resultados, he podido ver que los resultados usando ventana deslizante parecen mejorar mucho para algunas métricas y para otras no tanto. 

Puedes ver los resultados tu misma en la carpeta de script_results, donde se encuentra el resultado de ejecutar este script y puedes comparar con los resultados de referencia que teníamos de la versión anterior.

Un saludo,

Ángel,

**Comment by simber72** [comment]
Hola Angel,
he visto los resultados y me parece que el nuevo enfoque mejora  las métricas básicas en general. 
Bien!!


Un saludo,
Simona

**Comment by 844759** [comment]
Hola Simona,

He añadido el tiempo que se tarda para procesar las ventanas (time2window) a el código de prueba de test_detector_comparer_TEG.py para saber exactamente cuanto tiempo puede tardar, además de momento he adaptado el código de los programas de prueba de /energy donde he adaptado el codigo de tegdet_variants.py , tegdet_params_sensitivity.py y post_processing.py .

Un saludo,
Ángel,
