### ISSUE TITLE
Evaluar la precisión del tegdet-sliding-windows

### ISSUE THREAD

**Issue by simber72** [DiasporeUnizar/TEG#17]

**Comment by simber72** [comment]
Precisión--> métricas asociadas (accuracy) a la matriz de confusión (verdaderos positivos, verdaderos negativos, falsos positivos, falsos negativos)

Datos--> los mismos que los utilizados para la versión 1.1.0 pero adaptados al caso sliding windows:

- caso normal (sin ataques): training.csv + test_normal.csv 
- caso con ataques: training.csv + test_anomalous.csv

donde "+" = concatenación

**Comment by 844759** [comment]
Hola Simona,

He creado un documento para plasmar la comparativa en precisión del sistema al utilizar ventanas deslizantes versus la versión de matrices dispersas, lo puedes encontrar en el siguiente informe de google docs: https://docs.google.com/document/d/1qe2hf8Ajc_I-jeftqyGZF7Z-B006r49CB0YBF9x9SQk/edit?usp=sharing

Un saludo,

Ángel,
