### ISSUE TITLE
Corregir uso de la api en el caso de SlidingWindow

### ISSUE THREAD

**Issue by 844759** [DiasporeUnizar/TEG#19]

**Comment by 844759** [comment]
Hola Simona,

He realizado diversos cambios en el código de ventana deslizante, entre los cuales la clase SlidingWindow, entre las diversas cosas he modificado la clase ModelBuilder de la cual he eliminado los siguientes atributos de la clase para moverlos a SlidingWindow: 

```python
self.__tegg = tegg
self.__baseline = baseline
self.__mb = mb
``` 

De esta manera SlidingWindow no es tan dependiente de la clase de ModelBuilder, además tambien he cambiado el codigo de "tegdet_variants.py" y "tegdet_params_sensitivity", evitando el repetir codigo innecesario y haciendo que se utilice la interfaz de TEGDetector.

**Comment by simber72** [comment]
Hola Angel,
ahora los scripts son más simples (mejor).
He añadido unos comentarios para documentar los cambios en el teg.py (por actualizar) y cambiado el nombre de una función/método update_data -> update_global_graph

**Comment by 844759** [comment]
Hola Simona,

En cuanto a este comentario, la clase de ModelBuilder, ya no necesita la funcion que se menciona de update_model, puesto la información del modelo ahora se guarda en SlidingWindow al mover los tres atributos que te mencione anteriormente.

```python
updated `ModelBuilder` class adding the `update_data` to update the data of the model 
    ¿Has it been changed? 
``` 

Entonces respondiendo a la pregunta, si ha cambiado, por otro lado la funcion de update_mb en TEGDetector ya no es necesaria debido a la simplificación.

**Comment by simber72** [comment]
Hola Angel,

ok.
Creo que hay suficientes cambios para etiquetar esta versión como 2.0.0. Intentaré sintetizar los comentarios al comienzo del teg.py
Hay nuevas API (en la clase TEGDetector) y la "build_model" ya no es la misma de la versión v1.1.0
Si hay funciones/métodos que ya no son necesarios se pueden borrar.
