### ISSUE TITLE
Estructura repo para nueva versión de tegdet

### ISSUE THREAD

**Issue by simber72** [DiasporeUnizar/TEG#3]

**Comment by simber72** [comment]
Nueva versión de tegdet donde se intenta optimizar la parte de creación de grafos y comparación entre grafos utilizando matrices dispersas. Librería Python "oficial" (Scipy):

https://docs.scipy.org/doc/scipy/reference/sparse.html

**Comment by simber72** [comment]
Hola,
con respecto a la structura del repo: se puede seguir manteniendo la misma y crear una nueva rama para la versión con matrices dispersas.

SImona

**Comment by 844759** [comment]
Buenas, 

He creado una rama nueva en el repositorio llamada "Sparse" con la misma forma que la rama master, en la cual se encuentra la implementación con matrices dispersas, voy a empezar a realizar la evaluación de prestaciones.

Un saludo,
