### ISSUE TITLE
Evaluación comparativa de las prestaciones entre la nueva versión con matrices dispersas y la versión v1.0.1

### ISSUE THREAD

**Issue by simber72** [DiasporeUnizar/TEG#4]

**Comment by 844759** [comment]
Hola Simona,

He realizado un informe sobre las prestaciones de la nueva versión de tegdet, como ya te mencione hay una mejora en las prestaciones, de momento este análisis lo he enfocado usando la métrica de Hamming. 

Para ver el informe puedes pinchar en el siguiente enlace que te llevara a un documento de google docs, en el cual puedes comentar o modificarlo a tu gusto: https://docs.google.com/document/d/16Cs4FGaj7bf2Kp21-rGLHNqYzXBAKjySY3OdyYhNlvI/edit?usp=sharing

Un saludo,

**Comment by simber72** [comment]
Hola Angel,

he visto los resultados: gracias por el informe! 
Veo una buena mejora en la construcción de la secuencia de grafos y, en particular, del grafo global.

Una pregunta sobre el pico de memoria: 
¿Ocurre en la fase de construcción de las matrices "lil" cuando se analizan los datos de consumo? 

No hay mejora relevante en la comparación entre grafos: quizá se podría ver aquí si utilizar las operaciones implementadas para matrices dispersas mejoran los tiempos.
Se podría analizar para una métrica en concreto, por ejemplo la de Hamming, y ver si merece la pena cambiar la implementación de las demás.

Un saludo y buen finde,
Simona

**Comment by 844759** [comment]
Buenas Simona,

El pico de memoria sobre el que hablo es referente a la construcción de cada grafo, todo grafo inicial se inicia como una lil_array y parece que eso puede conllevar un gasto de memoria, estuve mirando la implementación de coo_array pero se sigue haciendo alguna actualización de índices en la matriz por lo que no parece ser mejor opción que lil_array.

En cuanto a utilizar operaciones de matrices dispersas en las métricas me pondré con ello para estudiar si conllevan una mejora sustancial en términos de tiempo.

Un saludo y buen finde,
Ángel,

**Comment by 844759** [comment]
Hola Simona,

He actualizado el documento con los datos exactos de memoria al construir todos los grafos, tanto en la versión original como en la versión desarrollada con matrices dispersas.

Un saludo,
Ángel

**Comment by simber72** [comment]
Hola Angel,
visto!
Gracias.

PS: ¿el miércoles quedamos un rato a las 15:00 en mi despacho? (no sé si te llegó el aviso de google calendar) Así vemos como plantear los próximos pasos a seguir.

**Comment by 844759** [comment]
Hola Simona,

Si me llego el aviso de Google, así que perfecto a las 15:00 nos vemos en tu despacho el miércoles.

Un saludo,
Ángel
