### ISSUE TITLE
Rediseñar la creación de las matrices para aprovechar la implementación dispersa de las matrices

### ISSUE THREAD

**Issue by 844759** [DiasporeUnizar/TEG#6]
Crear todas las matrices dispersas con un tamaño fijo para evitar operaciones de expansión de matrices

**Comment by simber72** [comment]
El tamaño fijo de las matrices es el tamaño del grafo "global" (suma de los grafos de la secuencia). El tamaño del grafo global se conoce a partir del parámetro nbins (--> ver self.__levels en la clase LevelExtractor)

**Comment by 844759** [comment]
Buenas Simona,

He conseguido adaptar lo que mencionaste para que todas las matrices tengan el mismo tamaño que el grafo global, he de decir que se han conseguido mejoras en tiempo y posiblemente en memoria, cuando termine el análisis más exhaustivo de tiempo te comento los tiempos exactos y la mejora que estos suponen.
