### ISSUE TITLE
Comprobar la corrección de la nueva versión (test_detector_comparer_TEG)

### ISSUE THREAD

**Issue by simber72** [DiasporeUnizar/TEG#7]

**Comment by 844759** [comment]
Hola Simona,

Tras conseguir la adaptación con matrices dispersas algunas metricas se han visto alteradas, en concreto las metricas KL, Canberra y Divergence salen mal al ejecutar el test en la nueva versión.

Estoy investigando el que puede suceder.

Un saludo,

**Comment by simber72** [comment]
Buenas,
ok.

Por favor, anota en la cabecera de los ficheros .py los mayores cambios que has hecho para tener una traza.

**Comment by 844759** [comment]
Hola Simona,

He estado investigando y por algún motivo el grafo global resultante al utilizar la métrica de KL, varia dependiendo de la versión con matrices dispersas y densas, esto puede explicar porque los valores de la métrica salen distintos.

He probado a cambiar las funciones "generate_graph" y "__sum_graph" para que se parecieran lo más posible a la versión de matrices densas, pero sigo sin averiguar la razón de porque algunos grafos se rellenan de manera ligeramente distinta a la versión original.

Un saludo,

Ángel

**Comment by simber72** [comment]
Hola Angel,

creo que hay que revisar la función de generación de grafos pues que los grafos que salen no son iguales a los que salían con la versión no optimizada (los grafos deberían ser los mismos, independientemente de la métrica utilizada).
He subido los grafos generados:

- versión no optimizada (main branch): /script_results/energy/graphs_teg_main.csv

- versión optimizada (sparse branch): /script_results/energy/graphs_teg_sparse.csv

Cada matriz tiene dimensión 32x32 (la dispersa ha sido convertida en densa)
Cada línea en los ficheros corresponde a una fila de una matriz: total 1920 filas (32 x 60)

He esbozado un script en /test: /test/test_graphs.py


Simona

**Comment by 844759** [comment]
Hola Simona,

He estado mirando la generación de grafos y lo que falla es el proceso de indexación al construir la matriz, es decir, las filas parece seleccionarlas bien, pero al seleccionar las columnas algunas veces se hace de forma erronea. Estoy investigando que puede ser exactamente el motivo para el cual las columnas se calculan incorrectamente en casos puntuales.

Un saludo,

**Comment by simber72** [comment]
HOla Angel,
sí le estoy echando un vistazo.
Me parece que esta línea:

self.__node_index = {node: idx for idx, node in enumerate(self.__nodes)}

hay que remplazarla porqué veo que fallan los elementos de la matriz que involucran niveles que tienen indice diferente....
No sé si esto vale:

self.__node_index = np.arange(max(values)+1)

Otra cosa: no entiendo porque pones una longitud mínima aquí:

bincounts = np.bincount(transitions, minlength=dim * dim)

Bueno, ya me dirás.
Buen finde semana.

Simona

**Comment by 844759** [comment]
Hola Simona,

He probado el cambio que dices y parece resultar en el mismo resultado, he vuelto a la implementación que había antes pero adaptándola a matrices dispersas sin realizar optimizaciones. 

La funcion tiene esta forma: 

def generate_graph(self, obs_discretized):
        """
        Generates the graph from the discretized observations "obs_discretized"
        """
        grouped = obs_discretized.groupby('DP').count()
        # Sets vertices: they are ordered according to the levels 
        self.__nodes = grouped.index.to_numpy()          
        self.__nodes_freq = grouped.to_numpy()

        attr = obs_discretized.DP.to_numpy()
        # Sets the adjacent matrix with the frequencies
        for i in range(attr.size - 1):
            row = self.__get_index(attr[i])
            col = self.__get_index(attr[i + 1])
            self.__matrix[row,col] += 1

        self.__matrix = self.__matrix.tocsr()

Es esencialmente la forma que tenia el codigo original, pero creo que la razón por la que se generan mal los grafos quizas tiene algo que ver con que ahora todas las matrices tienen el mismo tamaño, estoy investigando en ello.

En cuanto al argumento minlength se usa para garantizar que el vector de recuento de transiciones tenga el tamaño adecuado para representar todas las transiciones posibles en la matriz de transición, evitando cualquier posible error debido a la ausencia de algunas transiciones.

**Comment by simber72** [comment]
Hola,
he hecho algunas pruebas con la versión que tenías anterior y con el cambio:

---> self.__node_index = np.arange(max(values)+1)

Lo que me parece raros es que las matrices que genera la función son correctas, pero cuando se intenta recuperar las matrices una vez generados todos los grafos no se guardan algunas entradas.
Por ejemplo: la matriz del primer grafo 

======
al final de la función generate_graph
======
107,16,4,2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,28,12,2,3,1,2,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,18,34,11,3,2,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,3,15,6,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,4,3,4,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

========
al final de la función build_model(..) de TEGDetector
========
107,16,4,2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,28,12,2,3,1,2,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,18,34,11,3,2,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,3,15,6,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,4,3,4,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

con un diff de las dos se puede ver que los elementos diferentes están en (1,16) y (16,2) justo las transiciones en el log que tiene que ver con el nivel más alto 16:

2c2
< 18,28,12,2,3,1,2,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
---
> 18,28,12,2,3,1,2,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17c17
< 0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
---
> 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


No sé cual es el problema, pero da toda la pinta que tiene que ver con las conversiones de formato y las dimensiones.

Un saludo,
Simona

**Comment by 844759** [comment]
Hola Simona, 

He estado probando y yo he obtenido como matriz original utilizando el programa original de tegdet implementado en disperso la siguiente matriz para el primer grafo:

0,1,2,3,4,5,6,7,8,9,10,11
107,16,4,2,1,1,0,1,0,0,0,0
18,28,12,2,3,1,2,1,0,0,1,1
4,18,34,11,3,2,2,0,1,0,0,0
0,3,15,6,3,0,0,0,0,0,0,0
1,1,4,3,4,1,1,0,0,1,0,0
1,2,2,0,0,0,0,0,0,0,0,0
1,0,3,0,0,0,0,0,0,0,0,0
0,0,0,1,2,0,0,0,0,0,0,0
0,0,0,1,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,1,0,0,0,0
0,1,0,0,0,0,0,0,0,0,0,0
0,0,1,0,0,0,0,0,0,0,0,0

El problema es que varia bastante del primer caso almacenado en graphs_teg_main.csv, donde se almacenan las matrices originales, pero la primera matriz tiene dimensiones 12 x 12, no dimensiones mayores lo cual parece ser el caso ya que en la segunda fila hay un uno más allá del índice numero 12:

18,28,12,2,3,1,2,0,1,0,0,1,0,0,0,0,**1**,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Comment by 844759** [comment]
Hola Simona,

He estado mirando poco a poco donde podria llegar a cambiar la matriz entre las dos versiones y parece que el error se localiza a la hora de utilizar "expand_graph" y "resize_graph", porque introducen nuevos valores que no se localizaban anteriormente en la matriz.

**Comment by simber72** [comment]
Hola Angel,
haciendo pruebas veo que al final los grafos con la implementación que propusiste salen ok con los siguientes cambios:
(no he hecho el pull aún):

========================================================================
def generate_graph(self, obs_discretized):
        """
        Generates the graph from the discretized observations "obs_discretized".
        This version reduces unnecessary operations and optimizes the process of matrix filling.
        """
        # Extract node data and their frequency counts
        attr = obs_discretized['DP'].to_numpy()
        # Get unique values and counts
        values, counts = np.unique(attr, return_counts=True)
        self.__nodes = values
        self.__nodes_freq = counts
        #self.__node_index = {node: idx for idx, node in enumerate(self.__nodes)}
        #self.__node_index = np.arange(max(values)+1)

        dim = max(values)+1
        # Precompute row and column indices in one pass
        transitions = np.array([attr[i] * dim + attr[i + 1]
                                for i in range(len(attr) - 1)])

        # Count the transitions efficiently using bincount
        bincounts = np.bincount(transitions) #, minlength=dim * dim)
        
        nonzero_indices = np.nonzero(bincounts)[0]

        # Update the matrix using the counted transitions
        for idx in nonzero_indices:
            row, col = divmod(idx, dim)            
            self.__matrix[row, col] = bincounts[idx]

        # Convert to CSR after matrix construction
        self.__matrix.tocsr()
============================================================

Puesto que con esta implementación las matrices tienen todas el mismo tamaño (= al global graph) ya no hace falta la llamada a resize_graphs() en el calculo de las distancias (función compute_graphs_dist() de GraphDistanceCollector).

Los resultados son ok para todas las métricas en el test (test_detector_comparer_TEG.py) excepto que "Cosine" (donde habrá que ver qué pasa con las conversiones y tamaño arrays).

Simona

**Comment by 844759** [comment]
Hola Simona,

He conseguido arreglar la metrica de Cosine, simplemente truncando o rellenando las frecuencias de los nodos o las matrices:
```python
# Ensure both graphs have the same number of nodes and resize them if needed
        min_size = min(len(freq1), len(freq2))

        # Truncate or pad node frequencies to the same size
        freq1 = freq1[:min_size]
        freq2 = freq2[:min_size]

        # Truncate or pad matrices to the same size and keep them sparse
        mat1 = mat1[:min_size, :min_size]
        mat2 = mat2[:min_size, :min_size]
``` 

Con este cambio los resultados en las metricas son exactamente iguales al utilizar el script de test_detector_comparer_TEG.py, ahora me pondre a investigar que metricas se pueden optimizar usando la implementacion dispersa de las matrices.

Un saludo,
Ángel

**Comment by simber72** [comment]
Hola Angel,
el array de frecuencias se ha asignado en la generación del grafo:

```
values, counts = np.unique(attr, return_counts=True)
self.__nodes = values
self.__nodes_freq = counts
```
donde el número de elementos es igual al número de niveles observado en el log durante el periodo considerado (p.e., una semana)
Por ejemplo, en el caso de la primera semana, vimos que había 11 niveles  (no todos consecutivos):
Node values = [ 0  1  2  3  4  5  6  8  9 10 11 16]
Node freq = [132  69  75  27  16   5   5   3   1   1   1   1]

creo que se debería también modificar el vector de valores/frecuencias.... 
Node values = [ 0       1    2    3    4   5  6  0 8  9 10 11 12 13 14 15 16 ....32]
Node freq =     [132  69  75  27  16   5  5  0 3  1   1   1   1 0...0]

Simona

**Comment by 844759** [comment]
Hola Simona,

He arreglado lo que mencionas modificando el metodo generate_graph, he añadido las siguiente lineas: 

```python
# Get the graph dimension
dim = self.__matrix.shape[0]

# Get unique values and counts
values, counts = np.unique(attr, return_counts=True)

# Generate the node vector
self.__nodes = np.arange(0, dim)

# Build a numpyArray with as much 0 as dimension
self.__nodes_freq = np.zeros_like(self.__nodes)

# Fill the frequency with the values observated
self.__nodes_freq[np.isin(self.__nodes, values)] = counts
``` 

Con esto ya no es necesario hacer los cambios que mencionaba en Cosine

**Comment by simber72** [comment]
Hola Angel,

perfecto!

SImona
